"use strict";
(function () {
  const health = document.getElementById("ledgerHealth");
  const metrics = document.getElementById("ledgerMetrics");
  const graph = document.getElementById("integrityGraph");
  const textGraph = document.getElementById("integrityTextGraph");
  const graphStatus = document.getElementById("graphStatus");
  const refreshButton = document.getElementById("refreshIntegrity");
  function metric(label, value) { const box=document.createElement("div"); const dt=document.createElement("dt"); const dd=document.createElement("dd"); dt.textContent=label; dd.textContent=value; box.append(dt,dd); metrics.appendChild(box); }
  function label(node) { if(node.validity==="invalid") return `Invalid entry ${node.sequence}`; if(node.validity==="unchecked") return `Unchecked entry ${node.sequence}`; return `Valid entry ${node.sequence}`; }
  function renderNode(node,index) { if(index>0){const link=document.createElement("div"); link.className=`chain-link chain-link--${node.link_valid?"valid":"invalid"}`; link.textContent=node.link_valid?"→":"⚠ →"; link.setAttribute("aria-label",node.link_valid?"Valid previous-hash link":"Invalid previous-hash link"); graph.appendChild(link);} const card=document.createElement("article"); card.className=`chain-node chain-node--${node.validity}`; card.dataset.sequence=String(node.sequence); const h=document.createElement("h3"); h.textContent=`${node.validity==="invalid"?"⚠ ":node.validity==="valid"?"✓ ":"○ "}${label(node)}`; const tx=document.createElement("p"); tx.textContent=`Transaction: ${node.transaction_id}`; const hash=document.createElement("code"); hash.textContent=`Hash: ${node.hash_preview}`; hash.title=node.entry_hash; const previous=document.createElement("code"); previous.textContent=`Previous: ${node.previous_hash_preview}`; previous.title=node.previous_hash; card.append(h,tx,hash,previous); if(node.failure_type){const failure=document.createElement("p"); failure.className="chain-node__failure"; failure.textContent=`Failure: ${node.failure_type}`; card.appendChild(failure);} graph.appendChild(card); const item=document.createElement("li"); item.textContent=`${label(node)}. Transaction ${node.transaction_id}. Hash ${node.hash_preview}. Previous hash ${node.previous_hash_preview}. Link ${node.link_valid?"valid":"invalid"}.`; textGraph.appendChild(item); }
  function render(result) { window.AuditUi.clearElement(metrics); window.AuditUi.clearElement(graph); window.AuditUi.clearElement(textGraph); const state=result.valid?"success":"error"; window.AuditUi.setStatus(health,result.valid?`Ledger valid. ${result.entries_checked} entries checked.`:`Ledger invalid${result.first_invalid_sequence?` at sequence ${result.first_invalid_sequence}`:""}.`,state); metric("Total entries",String(result.total_entries)); metric("Entries checked",String(result.entries_checked)); metric("Ledger head",result.ledger_head_hash||"Empty ledger"); metric("Failure type",result.failure_type||"None"); if(!result.nodes.length){window.AuditUi.setStatus(graphStatus,"The ledger is empty. No chain nodes are available.","warning"); return;} result.nodes.forEach(renderNode); window.AuditUi.setStatus(graphStatus,`${result.nodes.length} nodes and ${result.edges.length} links rendered.`,state); }
  async function loadIntegrity(){window.AuditUi.setBusy(refreshButton,true,"Refreshing..."); window.AuditUi.setStatus(graphStatus,"Loading integrity graph...","info"); try{render(await window.AuditApi.request("/integrity/graph"));}catch(error){window.AuditUi.clearElement(graph); window.AuditUi.clearElement(textGraph); window.AuditUi.setStatus(health,"Ledger integrity is unavailable.","error"); window.AuditUi.setStatus(graphStatus,error.message||"The integrity graph could not be loaded.","error");}finally{window.AuditUi.setBusy(refreshButton,false);}}
  refreshButton.addEventListener("click",loadIntegrity); document.addEventListener("DOMContentLoaded",loadIntegrity);
})();
